name: Release Desktop

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows
            os: windows-latest
          - target: macos
            os: macos-latest
          - target: linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      HXCPP_COMPILE_CACHE: ${{ github.workspace }}/.hxcpp_cache
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Haxe
        uses: funkincrew/ci-haxe@v3.2.7
        with:
          haxe-version: 4.3.6

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: |
            .haxelib
            ${{ env.HXCPP_COMPILE_CACHE }}
          key: haxe-build-${{ matrix.target }}-${{ runner.os }}-${{ hashFiles('**/hmm.json') }}
          restore-keys: |
            haxe-build-${{ matrix.target }}-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          haxelib newrepo
          haxelib install hmm --never
          haxelib install hxp --never
          haxelib run hmm install
          haxelib list

      - name: Build game
        run: |
          haxelib run lime build ${{ matrix.target }} -release

      - name: Package build (Windows)
        if: matrix.target == 'windows'
        shell: pwsh
        run: Compress-Archive -Path export/release/windows/bin/* -DestinationPath FNF-Caleb-Windows.zip

      - name: Package build (MacOS)
        if: matrix.target == 'macos'
        run: |
          cd export/release/macos/bin
          zip -r "${{ github.workspace }}/FNF-Caleb-MacOS.zip" .

      - name: Package build (Linux)
        if: matrix.target == 'linux'
        run: |
          cd export/release/linux/bin
          zip -r "${{ github.workspace }}/FNF-Caleb-Linux.zip" .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: FNF-Caleb-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-build/FNF-Caleb-Windows.zip
            macos-build/FNF-Caleb-MacOS.zip
            linux-build/FNF-Caleb-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
